# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather_measurement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19weather_measurement.proto\x12\x05mimir\":\n\x12MeasurementRequest\x12\x12\n\nstart_time\x18\x01 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\"\xd1\x01\n\x0bMeasurement\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x10\n\x08\x61ir_temp\x18\x02 \x01(\t\x12\x10\n\x08pressure\x18\x03 \x01(\t\x12\x10\n\x08humidity\x18\x04 \x01(\t\x12\x13\n\x0bground_temp\x18\x05 \x01(\t\x12\n\n\x02uv\x18\x06 \x01(\t\x12\x12\n\nuv_risk_lv\x18\x07 \x01(\t\x12\x12\n\nwind_speed\x18\x08 \x01(\t\x12\x10\n\x08rainfall\x18\t \x01(\t\x12\x11\n\train_rate\x18\n \x01(\t\x12\x10\n\x08wind_dir\x18\x0b \x01(\t\"?\n\x13MeasurementResponse\x12(\n\x0cmeasurements\x18\x01 \x03(\x0b\x32\x12.mimir.Measurement\"\xef\x01\n\x16\x43urrentWeatherResponse\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x10\n\x08\x61ir_temp\x18\x02 \x01(\t\x12\x10\n\x08pressure\x18\x03 \x01(\t\x12\x10\n\x08humidity\x18\x04 \x01(\t\x12\x13\n\x0bground_temp\x18\x05 \x01(\t\x12\n\n\x02uv\x18\x06 \x01(\t\x12\x12\n\nuv_risk_lv\x18\x07 \x01(\t\x12\x12\n\nwind_speed\x18\x08 \x01(\t\x12\x11\n\twind_gust\x18\t \x01(\t\x12\x10\n\x08rainfall\x18\n \x01(\t\x12\x11\n\train_rate\x18\x0b \x01(\t\x12\x10\n\x08wind_dir\x18\x0c \x01(\t\")\n\x15\x43urrentWeatherRequest\x12\x10\n\x08\x64uration\x18\x01 \x01(\x03\x32\xb2\x01\n\rWeatherServer\x12K\n\x10get_measurements\x12\x19.mimir.MeasurementRequest\x1a\x1a.mimir.MeasurementResponse\"\x00\x12T\n\x13get_current_weather\x12\x1c.mimir.CurrentWeatherRequest\x1a\x1d.mimir.CurrentWeatherResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_measurement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEASUREMENTREQUEST._serialized_start=36
  _MEASUREMENTREQUEST._serialized_end=94
  _MEASUREMENT._serialized_start=97
  _MEASUREMENT._serialized_end=306
  _MEASUREMENTRESPONSE._serialized_start=308
  _MEASUREMENTRESPONSE._serialized_end=371
  _CURRENTWEATHERRESPONSE._serialized_start=374
  _CURRENTWEATHERRESPONSE._serialized_end=613
  _CURRENTWEATHERREQUEST._serialized_start=615
  _CURRENTWEATHERREQUEST._serialized_end=656
  _WEATHERSERVER._serialized_start=659
  _WEATHERSERVER._serialized_end=837
# @@protoc_insertion_point(module_scope)
